### ISSUE TITLE
Including thumbnails.php in a plugin?

### ISSUE THREAD

**Issue by jwight1234** [amnuts/jwplayer-thumbnail-preview-generator#1]
Hi Andrew,
I have a question (I am a newbie so bare with me) about how to use your command line tool. 
I want to include your thumbnails.php in a WordPress plugin but I am unsure of how to target the php file.

I have tried things like this:
$dir = ''path to WP plugin";
$ffmpeg = shell_exec($dir. 'include/thumbnails.php -h');
echo $ffmpeg;

just to see if i could echo out the help but no luck. What am i doing wrong?

cheers,

j

**Comment by amnuts** [comment]
As the thumbnails.php doesn't specify where your php binary is you'll need to call it when you do your shell exec; the system call will have this kind of structure:

`<path to php binary> <path to thumbnails.php> <options>`

If you're on a linux-style platform you can generally find out where your php binary is by doing `which php` and then copying the string returned to you. That way your shell_exec may end up looking, for example, like this:

`$ffmpeg = shell_exec("/usr/local/php/bin/php {$dir}/thumbnails.php -h");`

Hope that helps!

**Comment by jwight1234** [comment]
Hi Andrew,

Thank you very much I think that worked :D
Cheers

J
