### ISSUE TITLE
Image sprite and vtt file are out of order

### ISSUE THREAD

**Issue by cjhmdm** [amnuts/jwplayer-thumbnail-preview-generator#3]
When combining the images into a sprite, the images are being combined out of order (for example, the thumbnail-0001.jpg file is somewhere in the middle of the thumbnail.jpg sprite image.

Additionally, the order of the images output to the vtt file are out of order.

For example, here are a vew lines from the vtt file, which contains 110 total images:

```
00:00:00.000 --> 00:00:20.000
thumbnails/thumbnail-0007.jpg

00:00:20.000 --> 00:00:40.000
thumbnails/thumbnail-0083.jpg

00:00:40.000 --> 00:01:00.000
thumbnails/thumbnail-0003.jpg

00:01:00.000 --> 00:01:20.000
thumbnails/thumbnail-0044.jpg

00:01:20.000 --> 00:01:40.000
thumbnails/thumbnail-0099.jpg

00:01:40.000 --> 00:02:00.000
thumbnails/thumbnail-0032.jpg

00:02:00.000 --> 00:02:20.000
thumbnails/thumbnail-0031.jpg
```

update: I've done a bt to try and find the root of the issue, and so far have found this:

if I '$print_r($iterator);' directly below where the variable is initially declared, the output is always:

```
FilesystemIterator Object
(
    [pathName:SplFileInfo:private] => /path/to/output/thumbnails/thumbnail-0007.jpg
    [fileName:SplFileInfo:private] => thumbnail-0007.jpg
    [glob:DirectoryIterator:private] =>
    [subPathName:RecursiveDirectoryIterator:private] =>
)
```

So, for whatever reason, it always starts with "thumbnail-0007.jpg"

Also, the order is always exactly the same, regardless of how many times I run it (on the same video, haven't tried other videos yet). The initial order is always:
0007
0083
0003
0044
0099
0032
0031
etc
etc

This holds true for both 'print_r($files) as well as the output in the vtt file.

I should also note, the thumbnails themselves (when passing the v option) are created in the correct order, so there's no issue with the thumbnail generation itself, just the creation of the sprite and vtt files have the issue.

Update2: Changing the -t from 20 (my setting) to the default of 10, the array order changes due to the increased number of objects in the array, but the very first object is always thumbnail-0007.jpg

**Comment by cjhmdm** [comment]
I'm not sure if this is the most efficient way to handle it, but this seems to work on my end:
Change the following block:

```
$files = array_values(iterator_to_array(
    new CallbackFilterIterator($iterator, $filter)
));
```

to this:

```
$files = iterator_to_array(
    new CallbackFilterIterator($iterator, $filter)
);

function cmp($a,$b){
   if ($a->getFilename() == $b->getFilename()){
      return 0;
   }
   return ($a->getFilename() > $b->getFilename())?1:-1;
}

usort($files,'cmp');

$files = array_values($files);
```

**Comment by amnuts** [comment]
Thanks for that @cjhmdm - I wasn't experiencing that issue on my Windows box but see it now when firing up Ubuntu.  Have now fixed with the latest commit.
