### ISSUE TITLE
Video hosted on another server

### ISSUE THREAD

**Issue by elalemanyo** [amnuts/jwplayer-thumbnail-preview-generator#4]
Hi,
Is possible to adapt your script to use  a video that is hosted on aother server?

Thanks!

**Comment by amnuts** [comment]
It's not so much the script that needs to support remote files but ffmpeg, as the script is really a wrapper around that program.  A quick look online and it looks like ffmpeg does support remote files.  For example, this is a stackoverflow post on getting ffmpeg to use files on S3:

http://stackoverflow.com/questions/2677317/how-to-read-remote-video-on-amazon-s3-using-ffmpeg

Do a search for something like "ffmpeg remote video file" and you should find something that'd help.

The sanity check on line 74 uses is_readable which does support some URL wrappers, but you may need to check or change that code depending on how the file is accessed.

On 27 October 2015 06:04:46 GMT+00:00, "El Alemaño" notifications@github.com wrote:

> Hi,
> Is possible to adapt your script to use  a video that is hosted on
> aother server?
> 
> Thanks!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/amnuts/jwplayer-thumbnail-preview-generator/issues/4

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
