### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by campones** [amnuts/jwplayer-thumbnail-preview-generator#6]
Hello,

I have tested your script using command line, it works very well thanks.

I was wondering if I could use this script  through a cron job, and try to modify the input/output path so for example it could process a whole directory with several input files? 

As I dont see myself to create a vtt file manually for each videos, and also I realize modfifying the cms I m using (avs) is way out of my options (I m not a php coder..) I thought processing files via a cron time to time could be an option

**Comment by amnuts** [comment]
Yes, having it run from a cron job and input a number of files at once is totally possible.  I won't go into all kinds of details about setting up cron and whatnot, I'll assume you can do all that (or google for info on how).  But you could set up a php file to be called via cron and in that php file have something like:

``` php
<?php

chdir(__DIR__);
foreach (new DirectoryIterator(__DIR__.'/input') as $f) {
    if ($f->isDot()) {
        continue;
    }
    $dir = __DIR__ . '/output/' . $f->getBasename('.mp4');
    if (!file_exists($dir)) {
        mkdir($dir, 0775, true);
    }
    echo shell_exec(sprintf('php thumbnails.php -i "%s" -o "%s" 2>&1',
        $f->getPathname(),
        $dir
    ));
}
```

The above assumes that in the directory where the cron php file runs is a directory called 'input' and a directory called 'output', both of which should be readable by whatever user your cron runs as and the output also being writable.  It also assumes your files have the extension 'mp4'.

What it'll do is traverse the input directory for any files, create a new directory of the same name as the file within the output directory and then process the video, storing the thumbnails and vtt file in the newly created directory.

As this is just an example, the script doesn't do a lot of checking, cleaning up after itself, etc., but you should be able to implement anything pretty easily.  The above may give you a head-start, though.

If you need to add any flags to what you would normally call via the cli (such as -v for verbose thumbnail creation, or whatnot) then you'd drop that into the command in the shell_exec line.
