### ISSUE TITLE
Can't run script

### ISSUE THREAD

**Issue by Jonymahy** [amnuts/jwplayer-thumbnail-preview-generator#7]
Hello
I think have problem to run this script on php 5.3, do you have any version for php 5.3?

**Comment by amnuts** [comment]
Hi @Jonymahy; this is already covered in https://github.com/amnuts/jwplayer-thumbnail-preview-generator/issues/5 - follow the instructions there if you want to convert it to running on 5.3.

**Comment by Jonymahy** [comment]
Yes i have read commens there but can't make it to run with CallbackFilterIterator class.... looks that need to much php knowledge:(

**Comment by amnuts** [comment]
Basically just copy the code contained in the comment at http://php.net/manual/en/class.callbackfilteriterator.php#108803 into the start of the thumbnails script, changed the array syntax to the long format and that should pretty much be it.

**Comment by Jonymahy** [comment]
I just try, now is working but image sorting looks not good, sprite is generated but image is there is not sort from first...

**Comment by amnuts** [comment]
Can you paste your code up anywhere so I can see?  Maybe create a gist?

**Comment by Jonymahy** [comment]
Here is code http://pastebin.com/tQAhF6uK

**Comment by Jonymahy** [comment]
Any news? Maybe is problem there
Sort($files, SORT_NATURAL);
Bit i'm not sure

**Comment by amnuts** [comment]
Sorry, I hadn't had a chance to look at this yet or try it out on a 5.3 install.  Looking at it now, yes, you're more than likely right in that the sort is the issue.  The SORT_NATURAL flag only got introduced in PHP 5.4.

Try substituting that line for:

``` php
natcasesort($files);
```

instead and see if that works out for you.

Incidentally, PHP 5.3 had an end of life of 14 August, 2014. So if there is a chance for you to update PHP then you may want to consider it at some point.
