### ISSUE TITLE
PHP Notice with tbr array

### ISSUE THREAD

**Issue by dwoodworth** [amnuts/jwplayer-thumbnail-preview-generator#8]
Hi! First of all, this is perfect and exactly what I need, so thank you for that!!

Secondly, I'm getting an error that says: "PHP Notice:  Undefined offset: 1 in /media/WowzaContent/content/rebroadcast/thumbnails.php on line 101" when I try to run this, followed by "Could not find any thumbnails matching '/media/WowzaContent/content/rebroadcast/wed_thumbs/thumbnails/wed-7pm-wrc_live.stream-\d{4}.jpg'".

I'm using PHP 5.4 from the command line. I assume the second error is because no thumbnails were actually created, so of course the program can't find any.

Any thoughts on the first error?

**Comment by dwoodworth** [comment]
I realised I was using a very old version of FFMPEG (0.8) provided by the libav-tools package in Ubuntu. Apparently that is not compatible.

**Comment by amnuts** [comment]
If you just run `ffmpeg -i yourvideofilename.mp4 2>&1` (or whatever the command name would be if different for libav-tools) what output do you get?  If it's got the required elements but just in a different format output then it may be possible to tweak the regular expression to fit.

**Comment by dwoodworth** [comment]
This is the command I ran originally on 0.8:
`ffmpeg -i "Wed-7pm-wrc_live.stream.mp4"`
And here is the output:

```
ffmpeg version 0.8.17-4:0.8.17-0ubuntu0.12.04.1, Copyright (c) 2000-2014 the Libav developers
  built on Mar 16 2015 13:26:50 with gcc 4.6.3
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.

Seems stream 0 codec frame rate differs from container frame rate: 59.94 (60000/1001) -> 1000.00 (1000/1)
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Wed-7pm-wrc_live.stream.mp4':
  Metadata:
    major_brand     : f4v 
    minor_version   : 0
    compatible_brands: isommp42m4v 
    creation_time   : 2016-02-04 01:00:01
  Duration: 01:17:01.29, start: 0.000000, bitrate: 2645 kb/s
    Stream #0.0(eng): Video: h264 (Baseline), yuv420p, 720x480 [PAR 32:27 DAR 16:9], 2452 kb/s, 29.69 fps, 1k tbr, 90k tbn, 59.94 tbc
    Metadata:
      creation_time   : 2016-02-04 01:00:01
    Stream #0.1(eng): Audio: aac, 48000 Hz, stereo, s16, 189 kb/s
    Metadata:
      creation_time   : 2016-02-04 01:00:01
At least one output file must be specified
```

**Comment by dwoodworth** [comment]
It is working correctly now with the latest version of ffmpeg installed.

**Comment by amnuts** [comment]
I see that the above output had the tbr (framerate) as 1k which is understandable why it wasn't picked up by the regex (as it's looking only for digits and period).  That was probably glitchy on the older version of libav-tools.

Glad you were able to update and it resolve the issue!

**Comment by dwoodworth** [comment]
Yeah I thought it might have had something to do with the regex :)
Thanks again for this, makes my life so much easier!!
:+1:
